splash = false
ipc = true

wallpaper {
    monitor = DP-1
    path = ~/Media/Pictures/Wallpapers/mountains.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Media/Pictures/Wallpapers/mountains.jpg
    fit_mode = cover
}
